version: 2.1

jobs:

  build:

    docker:
      - image: circleci/python:3.8.1

    steps:
      - checkout

      - restore_cache:
          key: pipenv-packages-{{ checksum "Pipfile.lock" }}

      - run:
          name: Install Pipenv
          command: sudo pip install pipenv

      - run:
          name: Install Python dependencies
          command: make install

      - run:
          name: Python security static analysis check
          command: make security-check

      - run:
          name: Python style check
          command: make style-check

      - run:
          name: Run the server
          command: make serve
          no_output_timeout: 10s

      - save_cache:
          paths:
            - ./.venv
          key: pipenv-packages-{{ checksum "Pipfile.lock" }}
